### ISSUE TITLE
NaN in contribution complication for mock summary UI 

### ISSUE THREAD

**Issue by malsobay** [malsobay/pgg#10]
See complication for Cow in bottom right of grid. Never seen this in the main game before, so likely due to how complication values are generated for the mock UI? Not a showstopper, though. 

![Pasted Graphic 4](https://user-images.githubusercontent.com/79336354/206730785-50107439-4f78-428d-a824-599073345a12.png)

**Comment by npaton** [comment]
I saw this once. I went on to fix some other issues in the fake number generation. Then I couldn't reproduce it. I think it's fixed, but I am not 100% sure. I did reload 100 times, so like 2000 attempts.

**Comment by malsobay** [comment]
I haven't seen this again nor have I been able to reproduce, so I'll close.
