### ISSUE TITLE
Making better use of space with low N players

### ISSUE THREAD

**Issue by malsobay** [malsobay/pgg#11]
Screenshot below for N = 6 players (i.e., only 5 in the grid). The avatars seem unnecessarily crowded given the amount of whitespace available. Functional, but suboptimal. 

I don't understand the complexity behind making this work reliably, so I won't trivialize it. Investing in ironing out the kinks of an avatar grid layout component seems worth it, as I would wager this is a common use-case across multiplayer experiments; if it isn't, it likely will be after PGG is included as a default Empirica demo. 

![Pasted Graphic 3](https://user-images.githubusercontent.com/79336354/206731701-8782a653-dc99-4a68-864b-7d1959f37cd2.png)

**Comment by npaton** [comment]
I can confirm. It is less trivial than it might appear. I have made some improvements and run many tests. But I will need to keep relying on your feedback to tell me where you still see problems, as I cannot consistently reproduce the exact renderings of your screenshots. 👍

**Comment by malsobay** [comment]
Low N seems to be working well now 

N=20 seems to force a scroll for both contribution and outcome now (see below), but the complications seem easier to read in the summary stage 

Overall, I think we've likely arrived at a pilotable version. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/79336354/206969266-a1958e36-6d9c-40a1-87f2-61c2fac64b6a.png">

**Comment by npaton** [comment]
I've made some further improvements for N=20. Check out: https://github.com/malsobay/pgg/pull/13

The most significant change in on outcome, I moved the reward/deduction explanation to the left column. Not sure this is ok; let me know. If not, I don't have any other ideas at the moment. The biggest problem on that page is the text.

**Comment by malsobay** [comment]
Avatar complications LGTM. Tested with N=20 (but only in the instructions, which I assume should render identically to the real thing), and things are legible. 

My only reservation is that the chat window is now comically small as shown below (even though they can expand/collapse) and will cover the reward/deduction instructions, but I suppose this is the best we can do

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/79336354/207503570-aa40eda5-e058-4129-8b7e-a6a8e649e941.png">

**Comment by npaton** [comment]
Yeah, I know. It is. If we get to do another round of improvements, I'd like to fix chat, but as is, there's no simple solution. That and the details on hover in summary.

**Comment by malsobay** [comment]
Closing this for now, given that it's more or less functional
