### ISSUE TITLE
Critical: issue creating batches with multiple treatments

### ISSUE THREAD

**Issue by malsobay** [malsobay/pgg#15]
When creating a batch with multiple treatments, only 1 is shown in the sub-table (see example below). Need to test if this means that the games for the missing treatments are not being created, or if they're just not showing in the table. 

To reproduce, create a batch with at least two distinct treatments. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/79336354/210175272-97ffe013-d96a-46c5-aeb3-7cb9985a510d.png">

**Comment by npaton** [comment]
This is the expected behavior. You are setting up a batch with Simple assignment and a game count of 1. If you want 1 of each treatment, create a Complete assignment and set 1 game per treatment. 🙌 

See https://docsv1.empirica.ly/overview/randomization-and-batches for further details.

**Comment by malsobay** [comment]
Ah, I was confused by the game count. In that case, would it make sense to pop an alert when someone launches a batch with more treatments than games? There isn't any scenario where the current behavior for this edge case makes sense, is there?

**Comment by npaton** [comment]
This is not my area of expertise. I can see how you might want it to pick from a random treatment set. But you should talk with Abdullah, I don't know anything. 👍

**Comment by malsobay** [comment]
Thanks for clarifying what was going on; you know more than I'll forget 😅

I'll discuss further with Abdullah 👍🏼
