### ISSUE TITLE
Summary layout for low N (e.g. 3) overlaps and forces a scroll

### ISSUE THREAD

**Issue by malsobay** [malsobay/pgg#6]
**Issue:** In the **summary** stage, there are two related visual issues: 
1. The avatar complications overlap 
2. The layout forces a scroll, which hides the chat window (it's possible for a player to be completely oblivious to this, as the submission button doesn't require a scroll. 

This is the case with 3 and 4 players, but at larger N (e.g. 20) both issues aren't a problem. Screenshots below. 

![image](https://user-images.githubusercontent.com/79336354/206323528-5b645c07-9ec2-4e00-bc08-100b6a8d3388.png)
![image](https://user-images.githubusercontent.com/79336354/206323588-c05152f8-a73d-426e-a911-44baaa398244.png)

**Comment by malsobay** [comment]
Another example of a scroll being forced, this time in the contribution stage for 6 players... by default, the chat window isn't visible unless the player scrolls to the bottom 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/79336354/206379889-46402f2e-3f07-41f8-b613-ffe62b4f71fa.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/79336354/206379934-2c6472d2-91e1-4288-a491-16d5a1fee5ca.png">

**Comment by npaton** [comment]
This should be fixed, I can no longer reproduce.
