### ISSUE TITLE
Explanation of complication goes off screen

### ISSUE THREAD

**Issue by malsobay** [malsobay/pgg#8]
**Issue:** For some numbers of players (e.g. 6, shown below), the explanation of the deduction complication goes off the player's screen to the left. Likely related to #6, with avatars pushing other page content away? 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/79336354/206380475-6e2c2bf9-bdb9-40ad-86a6-745faee77dd6.png">

**Comment by npaton** [comment]
What minimum screen size are you testing for?

**Comment by npaton** [comment]
I don't see this problem at 1440 x 900.

<img width="1000" alt="Screenshot NP 2022-12-09 at 14 42 42@2x" src="https://user-images.githubusercontent.com/9678/206641392-ba5e06e1-1422-4af6-afe2-159b154f01b9.png">

**Comment by npaton** [comment]
Improvements:

<img width="953" alt="Screenshot NP 2022-12-09 at 14 54 05@2x" src="https://user-images.githubusercontent.com/9678/206643191-86ebd368-ff42-4877-bd5f-93e472635308.png">

**Comment by npaton** [comment]
Low player count:

<img width="949" alt="Screenshot NP 2022-12-09 at 14 55 01@2x" src="https://user-images.githubusercontent.com/9678/206643313-fa9effa7-71fd-4fbb-a22a-f1956bc19803.png">

**Comment by npaton** [comment]
This should be fixed with the latest push. 👍

**Comment by malsobay** [comment]
Looks fixed with #9 -- closing
